package com.scoder.common.swagger.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

import java.util.ArrayList;
import java.util.List;

@Configuration
@ConfigurationProperties(prefix = "swagger")
public class SwaggerProperties {
    /**
     * Enable or disable swagger
     */
    private Boolean enabled = true;

    /**
     * Base package to scan for APIs
     */
    private String basePackage = "";

    /**
     * Paths to include in the API documentation
     */
    private List<String> basePath = new ArrayList<>(List.of("/**"));

    /**
     * Paths to exclude from the API documentation
     */
    private List<String> excludePath = new ArrayList<>(List.of("/error", "/actuator/**"));

    /**
     * API documentation title
     */
    private String title = "API Documentation";

    /**
     * API documentation description
     */
    private String description = "API documentation generated by springdoc-openapi";

    /**
     * API version
     */
    private String version = "1.0";

    /**
     * Contact information for the API
     */
    private Contact contact = new Contact();

    // Getters and setters
    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public String getBasePackage() {
        return basePackage;
    }

    public void setBasePackage(String basePackage) {
        this.basePackage = basePackage;
    }

    public List<String> getBasePath() {
        return basePath;
    }

    public void setBasePath(List<String> basePath) {
        this.basePath = basePath;
    }

    public List<String> getExcludePath() {
        return excludePath;
    }

    public void setExcludePath(List<String> excludePath) {
        this.excludePath = excludePath;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public Contact getContact() {
        return contact;
    }

    public void setContact(Contact contact) {
        this.contact = contact;
    }

    public static class Contact {
        private String name = "Shawn Cui";
        private String url = "http://socder.co.uk";
        private String email = "shawn@scoder.co.uk";

        // Getters and setters
        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getUrl() {
            return url;
        }

        public void setUrl(String url) {
            this.url = url;
        }

        public String getEmail() {
            return email;
        }

        public void setEmail(String email) {
            this.email = email;
        }
    }
}